name: Autobuild
on: push

jobs:
  mister-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Check actions
        run: |
          ls /actions
      - name: Checkout Mister
        uses: actions/checkout@v2
        with:
          repository: MiSTer-devel/Main_MiSTer
          path: main_mister
      - name: Patch Mister
        run: |
          ./main/scripts/patchall.sh ./main_mister
      - name: Build Mister
        uses: docker://misterkun/toolchain
        with:
          args: make -C ./main_mister 
      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=`date +%Y%m%d`" >> $GITHUB_ENV
      - name: Copy Release
        run: |
          cp ./main_mister/MiSTer ./main/releases/MiSTer_`date +%Y%m%d`
      - name: Check in release
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Zakk
          author_email: zakk@rsdio.com
          message: "Automated Release ${{ env.RELEASE_DATE }}"
          add: "./releases/MiSTer_${{ env.RELEASE_DATE }}"
          cwd: './main'



