name: Autobuild
on: 
  push:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  mister-release:
    runs-on: ubuntu-latest
    env:
      DO_RUN_BUILD: YES
      LAST_MISTER_SHA: ''
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout Mister
        uses: actions/checkout@v2
        with:
          repository: MiSTer-devel/Main_MiSTer
          path: main_mister
      - name: Download calculate_db.py
        run: |
          curl https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/.github/calculate_db.py -o ./calculate_db.py
          chmod 755 ./calculate_db.py
      - name: Check if build needed
        if: github.event_name == 'schedule'
        run: |
          LAST_MISTER_RELEASE=`find ./main_mister/releases -type f | cut -d'_' -f3 | sort | tail -1`
          LAST_MISTER_SHA=`sha1sum ./main_mister/releases/MiSTer_${LAST_MISTER_RELEASE} | cut -f1 -d ' '`
          LAST_BUILD_SHA=""
          if [[ -f "./main/last_build_sum" ]]; then
            LAST_BUILD_SHA=`cat ./main/last_build_sum`
          fi
          echo "LAST_MISTER_SHA=${LAST_MISTER_SHA}" >> $GITHUB_ENV
          if [[ "$LAST_MISTER_SHA" == "$LAST_BUILD_SHA" ]]; then
            echo "DO_RUN_BUILD=NO" >> $GITHUB_ENV  
          fi
      - name: register ARM
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          docker run --rm --privileged hypriot/qemu-register
      - name: Patch Mister
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          ./main/scripts/patchall.sh ./main_mister
      - name: Build Mister
        if: env.DO_RUN_BUILD == 'YES'
        uses: docker://theypsilon/gcc-linaro:7.5.0
        with:
          args: make -C ./main_mister 
      - name: Set Release Date
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          echo "RELEASE_DATE=`date +%Y%m%d`" >> $GITHUB_ENV
      - name: Copy Release
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          cp ./main_mister/MiSTer ./main/releases/MiSTer_`date +%Y%m%d`
          mkdir -p ./main/downloader
          cp ./main_mister/MiSTer ./main/downloader
      - name: Set last mister checksum
        if: env.DO_RUN_BUILD == 'YES' && env.LAST_MISTER_SHA != ''
        run: |
          echo "${LAST_MISTER_SHA}" > ./main/last_build_sum
      - name: Check in release
        if: env.DO_RUN_BUILD == 'YES'
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Zakk
          author_email: zakk@rsdio.com
          message: "Automated Release ${{ env.RELEASE_DATE }}"
          add: '["./releases/MiSTer_${{ env.RELEASE_DATE }}", "last_build_sum", "./downloader/MiSTer"]'
          cwd: './main'
      - name: Create downloader database
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          git config --global user.email "zakk@rsdio.com"
          git config --global user.name "Automated release bot"
          rm db.json.zip
          ../../calculate_db.py
        working-directory: ./main/downloader
        env:
          DB_ID: mister_zqol
          DB_URL: https://raw.githubusercontent.com/zakk4223/Main_Mister_ZQol/main/downloader/db.json.zip
          BASE_FILES_URL: https://raw.githubusercontent.com/zakk4223/Main_Mister_ZQol/%s/downloader/

