name: Autobuild
on: 
  push:
  workflow_dispatch:
jobs:
  mister-release:
    runs-on: ubuntu-latest
    env:
      DO_RUN_BUILD: YES
      DB_ID: zakk_main
      LAST_MISTER_SHA: ''
      LAST_DISTDB_SHA: ''
      FINDER_IGNORE: ./last_build_sum ./last_db_sum ./patches ./releases ./scripts ./wip
    steps:
      - name: Install apt-get utilities
        run: sudo apt-get install detox sharutils
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout Mister
        uses: actions/checkout@v2
        with:
          repository: MiSTer-devel/Main_MiSTer
          path: main_mister
      - name: Check if build needed
        if: github.event_name == 'schedule'
        run: |
          cd main_mister 
          LAST_MISTER_SHA=`git log -n 1 --pretty=format:"%H"`
          cd ..
          LAST_BUILD_SHA=""
          if [[ -f "./main/last_build_sum" ]]; then
            LAST_BUILD_SHA=`cat ./main/last_build_sum`
          fi
          echo "LAST_MISTER_SHA=${LAST_MISTER_SHA}" >> $GITHUB_ENV

          if [[ "$LAST_MISTER_SHA" == "$LAST_BUILD_SHA" ]]; then
            echo "DO_RUN_BUILD=NO" >> $GITHUB_ENV  
          fi
      - name: Patch Mister
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          ./main/scripts/patchall.sh ./main_mister
      - name: Build Mister
        if: env.DO_RUN_BUILD == 'YES'
        uses: docker://theypsilon/gcc-arm:10.2-2020.11
        with:
          args: make -C ./main_mister 
      - name: Set Release Date
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          echo "RELEASE_DATE=`date +%Y%m%d`" >> $GITHUB_ENV
      - name: Copy Release
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          MISTER_BIN_NAME=MiSTer_`date +%Y%m%d`
          echo "MISTER_BINARY_NAME=${MISTER_BIN_NAME}" >> $GITHUB_ENV
          cp ./main_mister/MiSTer ./main/releases/$MISTER_BIN_NAME
          cp ./main_mister/MiSTer ./main/downloader/MiSTer_zakk
          touch ./main/downloader/README.md
          if [ -f ./main/downloader/db.json.zip ]; then rm ./main/downloader/db.json.zip; fi
          if [ -f ./main/downloader/db.json ]; then rm ./main/downloader/db.json; fi
      - name: Set last mister checksum
        if: env.DO_RUN_BUILD == 'YES' && env.LAST_MISTER_SHA != ''
        run: |
          echo "${LAST_MISTER_SHA}" > ./main/last_build_sum
      - name: Update database json
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          cd ./main/
          set -o pipefail && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py | python3 -
          git checkout -f main 
          cd downloader
          if [ -f ./db.json ]; then zip ./db.json.zip ./db.json ..; fi
      - name: Check in release
        if: env.DO_RUN_BUILD == 'YES' || env.DO_DB_BUILD == 'YES'
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Zakk
          author_email: zakk@rsdio.com
          message: "Automated Release ${{ env.RELEASE_DATE }}"
          add: '["./releases/MiSTer_${{ env.RELEASE_DATE }}", "last_build_sum", "./downloader/MiSTer_zakk", "./downloader/db.json.zip", "./downloader/db.json"]'
          cwd: './main'

