name: Autobuild
on: 
  push:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  mister-release:
    runs-on: ubuntu-latest
    env:
      DO_RUN_BUILD: YES
      DO_DB_BUILD: YES
      LAST_MISTER_SHA: ''
      LAST_DISTDB_SHA: ''
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout Mister
        uses: actions/checkout@v2
        with:
          repository: MiSTer-devel/Main_MiSTer
          path: main_mister
      - name: Download distribution MiSTer
        run: |
          curl https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/MiSTer -o MiSTer.dist
      - name: Download distribution db.json.zip
        run: |
          curl https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip -o db.json-dist.zip
      - name: Extract db.json.zip
        run: |
          unzip db.json-dist.zip
          mv db.json db.json.dist
      - name: Check if build needed
        if: github.event_name == 'schedule'
        run: |
          LAST_MISTER_SHA=`sha1sum ./MiSTer.dist | cut -f1 -d ' '`
          LAST_DISTDB_SHA=`sha1sum ./db.json-dist.zip | cut -f1 -d ' '`
          LAST_BUILD_SHA=""
          LAST_ZDB_SHA=""
          if [[ -f "./main/last_build_sum" ]]; then
            LAST_BUILD_SHA=`cat ./main/last_build_sum`
          fi
          if [[ -f "./main/last_db_sum" ]]; then
            LAST_ZDB_SHA=`cat ./main/last_db_sum`
          fi
          echo "LAST_DISTDB_SHA=${LAST_DISTDB_SHA}" >> $GITHUB_ENV
          echo "LAST_MISTER_SHA=${LAST_MISTER_SHA}" >> $GITHUB_ENV

          if [[ "$LAST_DISTDB_SHA" == "$LAST_ZDB_SHA" ]]; then
            echo "DO_DB_BUILD=NO" >> $GITHUB_ENV
          fi

          if [[ "$LAST_MISTER_SHA" == "$LAST_BUILD_SHA" ]]; then
            echo "DO_RUN_BUILD=NO" >> $GITHUB_ENV  
          fi
      - name: Patch Mister
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          ./main/scripts/patchall.sh ./main_mister
      - name: Build Mister
        if: env.DO_RUN_BUILD == 'YES'
        uses: docker://theypsilon/gcc-arm:10.2-2020.11
        with:
          args: make -C ./main_mister 
      - name: Set Release Date
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          echo "RELEASE_DATE=`date +%Y%m%d`" >> $GITHUB_ENV
      - name: Copy Release
        if: env.DO_RUN_BUILD == 'YES'
        run: |
          cp ./main_mister/MiSTer ./main/releases/MiSTer_`date +%Y%m%d`
          mkdir -p ./main/downloader
          cp ./main_mister/MiSTer ./main/downloader
      - name: Set last mister checksum
        if: env.DO_RUN_BUILD == 'YES' && env.LAST_MISTER_SHA != ''
        run: |
          echo "${LAST_MISTER_SHA}" > ./main/last_build_sum
      - name: Update database json
        if: env.DO_RUN_BUILD == 'YES' || env.DO_DB_BUILD == 'YES'
        run: |
          rm db.json-dist.zip
          NEW_MISTER_MD5=`md5sum ./main/downloader/MiSTer | cut -f1 -d ' '`
          NEW_MISTER_SIZE=`wc -c ./main/downloader/MiSTer | cut -f1 -d ' '`
          NEW_MISTER_URL="https://raw.githubusercontent.com/zakk4223/Main_Mister_ZQol/main/downloader/MiSTer"
          jq --arg msum "$NEW_MISTER_MD5" --argjson msize "$NEW_MISTER_SIZE" --arg murl "$NEW_MISTER_URL" '.files.MiSTer.hash = $msum | .files.MiSTer.size = $msize | .files.MiSTer.url = $murl' db.json.dist > db.json
          zip db.json.zip db.json
          cp ./db.json.zip ./main/downloader
          echo "${LAST_DISTDB_SHA}" > ./main/last_db_sum
      - name: Check in release
        if: env.DO_RUN_BUILD == 'YES' || env.DO_DB_BUILD == 'YES'
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Zakk
          author_email: zakk@rsdio.com
          message: "Automated Release ${{ env.RELEASE_DATE }}"
          add: '["./releases/MiSTer_${{ env.RELEASE_DATE }}", "last_db_sum", "last_build_sum", "./downloader/MiSTer", "./downloader/db.json.zip"]'
          cwd: './main'

